### ISSUE TITLE
Cannot create output file '.\result\Groundtrue202009252115.png'.

### ISSUE THREAD

**Issue by PaulWU1996** [yangliuav/Multi-target-tracking-based-on-RFS--PHD-filter-and-Particle-flow#3]
文件夹路径新增result路径 并在initialization.m中增加addpath语句 将result路径增添至工作空间中

**Comment by yangliuav** [comment]
这个是在哪一行？

**Comment by PaulWU1996** [comment]
我看看呀

**Comment by yangliuav** [comment]
是不是line 115 of  generateMeasurements

**Comment by PaulWU1996** [comment]
> 是不是line 115 of generateMeasurements

对的！

**Comment by yangliuav** [comment]
好的，解决了

**Comment by PaulWU1996** [comment]
> 是不是line 115 of generateMeasurements


> 好的，解决了

好的呀 我给git 下来试试看 还有一个xxt变量未定义的 以及 变量H的问题

**Comment by yangliuav** [comment]
我都解决完一起git

**Comment by PaulWU1996** [comment]
> 我都解决完一起git
好哒！

**Comment by yangliuav** [comment]
只是备注一下，这个问题是由windows路径问题
