### ISSUE TITLE
未被定义的变量xxt在particleFlowPHD line104

### ISSUE THREAD

**Issue by PaulWU1996** [yangliuav/Multi-target-tracking-based-on-RFS--PHD-filter-and-Particle-flow#5]
Unrecognized function or variable 'xxt'.

Error in particleFlowPHD (line 104)

speaker的position是从xxt中获取出来的， 但是前后并没有xxt的信息或定义

if isfield(setup.inp,'x_all')
                for i = 1: setup.Ac.nspeaker
                    x_pos_i = xxt((i-1)*4+1,:);
                    y_pos_i = xxt((i-1)*4+2,:);
                    plot(x_pos_i,y_pos_i,'-s','Color',cmap(i,:),'LineWidth',5,'MarkerSize',20);  %# Plot each column with a
                end
end

**Comment by yangliuav** [comment]
参考一下，SMC-PHD.m 的 line 188
if isfield(setup.inp,'x_all')
                xx = cell2mat(setup.inp.x_all);
                xxt  =xx(:,tt);
                for i = 1: setup.Ac.nspeaker
                    x_pos_i = xxt((i-1)*4+1,:);
                    y_pos_i = xxt((i-1)*4+2,:);
                    plot(x_pos_i,y_pos_i,'-s','Color',cmap(i,:),'LineWidth',5,'MarkerSize',20);  %# Plot each column with a
                end
                for i = 1:size(xxt,1)/4
                    truex([1,2],i) = xxt([(i-1)*4+1,(i-1)*4+2],1);
                end
            end

**Comment by PaulWU1996** [comment]
解决
